'use client';

import ReactMarkdown, { defaultUrlTransform } from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeRaw from 'rehype-raw';
import rehypeKatex from 'rehype-katex';
import rehypeSanitize from 'rehype-sanitize';
import rehypeSlug from 'rehype-slug';
import 'katex/dist/katex.min.css';

import { remarkCallouts } from '@/lib/markdown/remark-callouts';
import { remarkCodeMeta } from '@/lib/markdown/remark-code-meta';
import { sanitizeSchema } from '@/lib/markdown/sanitize-schema';
import { rehypeCollapsibleSections } from '@/lib/markdown/rehype-collapsible';
import { parseEmbed } from '@/lib/markdown/embeds';
import { CodeBlock } from './code-block';
import { Mermaid } from './mermaid';
import { Callout } from './callout';
import { MarkdownImage } from './markdown-image';
import { Embed } from './embed';
import { CollapsibleSection } from './collapsible-section';

const REMARK_PLUGINS = [remarkGfm, remarkMath, remarkCallouts, remarkCodeMeta];

/**
 * react-markdown runs its own URL filter before any rehype plugin, and it blanks
 * `data:` outright — which silently deleted images pasted into the editor, leaving
 * an empty paragraph. Inline images are re-allowed for `<img src>` only; every other
 * URL, including `data:text/html` in an `href`, still goes through the default.
 */
const urlTransform = (url, key, node) => {
  if (key === 'src' && node?.tagName === 'img' && /^data:image\/(png|jpe?g|gif|webp|avif|svg\+xml);/i.test(url)) {
    return url;
  }
  return defaultUrlTransform(url);
};

/**
 * `rehypeSlug` runs *after* sanitization so heading ids are generated by us rather
 * than passed through from the document, and it uses GitHub's slug algorithm so
 * `[jump](#installation)` inside a README resolves to the same anchor it would on
 * GitHub. Previously headings had no ids at render time at all — they were assigned
 * imperatively after mount, which left exported HTML and PDFs with no anchors.
 */
const REHYPE_PLUGINS = [rehypeRaw, [rehypeSanitize, sanitizeSchema], rehypeSlug, rehypeKatex];
const REHYPE_PLUGINS_COLLAPSIBLE = [...REHYPE_PLUGINS, rehypeCollapsibleSections];

const nodeText = (node) =>
  (node?.children ?? []).map((c) => (c.type === 'text' ? c.value : nodeText(c))).join('');

const components = {
  pre({ node, children }) {
    const codeEl = node?.children?.find((c) => c.tagName === 'code');
    if (!codeEl) {
      return (
        <pre className="my-4 overflow-x-auto rounded-lg border border-border bg-muted/50 p-4 text-sm">
          {children}
        </pre>
      );
    }
    const className = codeEl.properties?.className?.[0] ?? '';
    const lang = /language-(\S+)/.exec(className)?.[1];
    const code = nodeText(codeEl).replace(/\n$/, '');
    // The fence's info string after the language — e.g. ```js {2,4-6} — carries the
    // line-highlight request.
    const meta = codeEl.properties?.dataMeta ?? '';
    return lang === 'mermaid' ? (
      <Mermaid code={code} />
    ) : (
      <CodeBlock code={code} lang={lang} meta={meta} />
    );
  },
  code({ children }) {
    return (
      <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[0.85em]">{children}</code>
    );
  },
  blockquote({ node, children }) {
    const cls = node?.properties?.className;
    const callout = Array.isArray(cls) ? cls.find((c) => c.startsWith('callout-')) : null;
    if (callout) return <Callout type={callout.replace('callout-', '')}>{children}</Callout>;
    return (
      <blockquote className="my-4 border-l-4 border-border pl-4 italic text-muted-foreground">
        {children}
      </blockquote>
    );
  },
  img: ({ src, alt, width, height, title }) => (
    <MarkdownImage src={src} alt={alt} width={width} height={height} title={title} />
  ),
  p({ node, children }) {
    const kids = node?.children ?? [];
    if (kids.length === 1 && kids[0].type === 'element' && kids[0].tagName === 'a') {
      const embed = parseEmbed(kids[0].properties?.href);
      if (embed) return <Embed embed={embed} />;
    }
    return <p className="my-4 leading-7">{children}</p>;
  },
  a({ href, children, ...rest }) {
    const external = /^https?:\/\//i.test(href || '');
    return (
      <a
        href={href}
        {...rest}
        {...(external ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
        className="font-medium text-primary underline underline-offset-2 hover:no-underline"
      >
        {children}
      </a>
    );
  },
  section({ node, children, ...rest }) {
    const depth = Number(node?.properties?.dataDepth) || undefined;
    if (!depth) return <section {...rest}>{children}</section>;
    return <CollapsibleSection depth={depth}>{children}</CollapsibleSection>;
  },
};

export function Markdown({ content = '', collapsibleSections = false }) {
  return (
    <div className="markdown-body min-w-0">
      <ReactMarkdown
        remarkPlugins={REMARK_PLUGINS}
        rehypePlugins={collapsibleSections ? REHYPE_PLUGINS_COLLAPSIBLE : REHYPE_PLUGINS}
        urlTransform={urlTransform}
        components={components}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
